### ISSUE TITLE
practical1.md

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/SBC361-programming-in-R#6]
A few things noticed today  (i'm sure you will also have found things that should be addressed before friday):

 - [x]  When they are subsetting the puromycin table, the `subset()` approach is preferred. It should thus come before the confusing [,] approach
 - [x] When calling a function such as subset, we should name the arguments, e.g. subset(x = puromycin_data, subset = conc < rate)

**Comment by bmpvieira** [comment]
Other things (we are fixing):
- [ ] Many were not aware that a vector (e.g., the result of `3:5` or `c(8, 13, 21)`) could be used to retrieve elements of another vector (e.g., `vec[c(8, 13, 21)]`). I had to explain this several times and very slowly so that could make the connection. Some would figure out that ```c``` was needed and would start putting it randomly anywhere between `[]` and `()`, or try to assign something to it (`c<-`), so I had to make it very clear that `c` was a function to create a vector, and then they would understand it.

- [ ] Kim told me she had to explain booleans a lot, but I only did it 2 or 3 times and it was for each case a different issue.

- [ ] The last two regex are really hard (even for instructors) and require a lot of [perl voodoo] (http://perldoc.perl.org/perlreref.html) (e.g., `replacement = "\\1\\U\\2\\L\\3"`). We can keep them but make the penultimate also "hacker" level. We should at the end or after the practical give the solution and explain.

**Comment by yannickwurm** [comment]
waht do you mean with last two?  which questions?

**Comment by bmpvieira** [comment]
Third bullet point of question 31, and question 32.

#### Q31. Add three additional columns to the `reptile_data` table:
* one containing only the identifier numbers (e.g. 1423 without the “ID”)
* one column containing only the genus (e.g. Bellatorias)
* **one containing only the species (excluding the subspecies, e.g. tympanum)**
Hint - try to decompose this task, the solution is not a “one-liner”. Make use of the functions you have just learnt and focus on extracting the numbers, genus, and species, rather than the “add new columns” bit.

#### Hacker Q32.  Figure out how to “capture” the first letter of the species, and transform it to make it uppercase. Do this in a generic manner (that would work on a table of thousands of species).
Hint - look into the help page of “gsub”, especially the explanation for the “replacement” parameter, as well as the examples at the bottom of the help page.

**Comment by lrsantiago** [comment]
I have put the third bullet point of question 31 as an additional part of the question 32. As we think it is difficult enough, it is going to be part of the hacker question as well.

**Comment by yannickwurm** [comment]
"one containing only the species (excluding the subspecies, e.g. tympanum) Hint - try to decompose this task, the solution is not a “one-liner”. Make use of the functions you have just learnt and focus on extracting the numbers, genus, and species, rather than the “add new columns” bit."


Please revert your chagne.
you guys are thinking too complicated. Perl is not needed for this. capturing is not needed.


something along the following lines works (from memory, you may need to finetune)

    no_genus     <- gsub(patt = "^ID[0-9]+:[A-z]+ ", repl="", x = names)
    only_species <- gsub(patt = " [a-z]+$", repl="", x=no_genus)

or a hacker might combien the two:

    gsub(patt = "(^ID[0-9]+:[A-z]+ )|( [a-z]+$)", repl="", x = names)


(in general it is better to be more specific in your regexp to minimise risks (e.g. using + rather than * when appropriate, using [a-z] rather than . when appropriate)

++

**Comment by lrsantiago** [comment]
I also had one solution for those questions in two steps. I also have a solution in one line without using perl, it is working well, so, I'm gonna change it back and explain it in the last 10-15 min of the practical on Friday.

**Comment by yannickwurm** [comment]
@lrsantiago please close this once you have fully read and understood my previous comment.
